### ISSUE TITLE
What to do next take, 2.

### ISSUE THREAD

**Issue by covers1624** [TheCBProject/ThermalExpansion#2]
So.
It compiles.
But there is still a lot of work to be done.

What is being worked on:
- [X] All Gui's work
- [X] All machines function and auto spit items.
- [X] Ducts transport all the things.
- [X] ThermalFoundation feature complete as per 1.7.
- [x] Sounds.
- [x] All machine models done.
- [x] All Thermal Dynamics done.
- [x] All Thermal Expansion done.

Other things that need to be done.
- [ ] All assets to snake_case in prep for 1.11's resource changes.
- [ ] All modId's to lowercase.
- [ ] Version checker to be moved to forge.
- [x] Use the version scheme forge does.
- [ ] Setup ForgeGradle build system and possble maven deployment?

That's it really.
Ive spoken with @KingLemming, This repo is the "official" port.

**Comment by p455w0rd** [comment]
as of today, all TE blocks are rendering 100%

**Comment by covers1624** [comment]
Initial post updated.
