### ISSUE TITLE
Crash when placing lamp (and luminum lamp too)

### ISSUE THREAD

**Issue by miuirussia** [TheCBProject/ThermalExpansion#4]
Tesselating block model
[crash-2017-01-05_20.24.01-client.txt](https://github.com/TheCBProject/ThermalExpansion/files/688032/crash-2017-01-05_20.24.01-client.txt)

**Comment by miuirussia** [comment]
OptiFine bug, sorry

**Comment by covers1624** [comment]
@miuirussia Are you with MMD or FTB? If you have compiled the mod yourself you wont get support, it is not ready for release yet.

**Comment by miuirussia** [comment]
I compiled myself, and looking for bugs

**Comment by covers1624** [comment]
I appreciate the effort you are going to, but at this point im concidering it almost stable, just some fluffing to do. Thanks anyway.

**Comment by miuirussia** [comment]
Yes, stable, but some bugs here:
- Connecting Magma Crucible with Fluid Transposer not working (side by side connection)
- Buckets not using new rendering model as forge-bucket
- Activator, Breaker, Collector, Nullifier, Buffer not rendering
for now it is all that I have found.
