### ISSUE TITLE
Few bugs and sugressions

### ISSUE THREAD

**Issue by miuirussia** [TheCBProject/ThermalExpansion#5]
- [x] Connecting Magma Crucible with Fluid Transposer not working (side by side connection)
- [x] Reactant Dynamo not filling with fluid from back side, all the sides working
- [x] Activator, Breaker, Collector, Nullifier, Buffer not rendering
- [ ] Buckets not using new rendering model as forge-bucket
- [ ] Fluids not rendering in Fluid Transposer model
- [ ] Replace CoFH Energy API to Forge Energy
- [ ] Florbs are not shown in flight

For now it is all that I have found. Thanks for re-animating these amazing mods!

**Comment by P3pp3rF1y** [comment]
I am pretty sure this stuff was working previously and it was recently pretty deeply tested so what you're seeing is likely issue with how you have built the mod.

**Comment by miuirussia** [comment]
gradle setupDecompWorkspace build

**Comment by covers1624** [comment]
Nope, its an actually issue, i rushed the cap rewrite, still a few instance of checks here and there.

**Comment by miuirussia** [comment]
Buckets not using new rendering model as forge-bucket - done, in pull requests

**Comment by miuirussia** [comment]
Fluids not rendering in Magma Crucible and Fluid Transposer model:
in Magma Crucible - working
in Fluid Transposer - not showing

**Comment by covers1624** [comment]
I understand you are trying to help but its slowing me down. as it is right now, im rewriting a lot of the fluid interaction including for the buckets and most of the issues you have reported are now fixed.
